/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PeopleGUI;

import javax.swing.JOptionPane;
import Classes.VaccineRegistration;
import HelperClasses.State;
import Classes.VaccinationCenter;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Eric
 */
public class PeopleRegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    public PeopleRegistrationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerfor = new javax.swing.ButtonGroup();
        closecontact = new javax.swing.ButtonGroup();
        healthcondition = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblRegistrationId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtIcPassport = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        closecontactno = new javax.swing.JRadioButton();
        closecontactyes = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btncancelregistration = new javax.swing.JButton();
        txtHealthCondition = new javax.swing.JTextField();
        cmbVaccinationCenter = new javax.swing.JComboBox<>();
        cmbState = new javax.swing.JComboBox<>();
        btnsubmitregistration = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 100));
        setMinimumSize(new java.awt.Dimension(900, 530));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(186, 221, 212));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 530));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 530));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 530));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(220, 530));
        jPanel2.setMinimumSize(new java.awt.Dimension(220, 530));
        jPanel2.setPreferredSize(new java.awt.Dimension(220, 530));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel2.setText("Registration");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel4.setText("Programme");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel5.setText("Vaccination");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/biglogo.png"))); // NOI18N

        lblRegistrationId.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        lblRegistrationId.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrationId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrationId.setText("Appointment ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(47, 47, 47))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRegistrationId, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegistrationId, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 26)); // NOI18N
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 0, -1, -1));

        txtContact.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtContact.setBorder(null);
        jPanel1.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 260, 30));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel6.setText("Notifications for appointment booking and reminders will be sent to your number and email.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        jLabel9.setText("Contact Number");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        jLabel10.setText("Email");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        txtEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 260, 30));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        jLabel12.setText("Full Name as per IC / Passport");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        txtIcPassport.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtIcPassport.setBorder(null);
        txtIcPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIcPassportActionPerformed(evt);
            }
        });
        jPanel1.add(txtIcPassport, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 260, 30));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        jLabel13.setText("NRIC (Citizen) / Passport (Non-citizen)");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        txtName.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtName.setBorder(null);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 260, 30));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 19)); // NOI18N
        jLabel8.setText("Do you have any health condition?");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel14.setText("Have you had close contact to confirmed or suspected case of COVID-19 within");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel15.setText("14 days?");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        closecontactno.setBackground(new java.awt.Color(186, 221, 212));
        closecontact.add(closecontactno);
        closecontactno.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        closecontactno.setText("No");
        closecontactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closecontactnoActionPerformed(evt);
            }
        });
        jPanel1.add(closecontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        closecontactyes.setBackground(new java.awt.Color(186, 221, 212));
        closecontact.add(closecontactyes);
        closecontactyes.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        closecontactyes.setText("Yes");
        closecontactyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closecontactyesActionPerformed(evt);
            }
        });
        jPanel1.add(closecontactyes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setText("Preferred Vaccination Centre");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel17.setText("State");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        btncancelregistration.setBackground(new java.awt.Color(82, 137, 128));
        btncancelregistration.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btncancelregistration.setText("Cancel");
        btncancelregistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelregistrationMouseClicked(evt);
            }
        });
        btncancelregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelregistrationActionPerformed(evt);
            }
        });
        jPanel1.add(btncancelregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 100, 40));

        txtHealthCondition.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtHealthCondition.setBorder(null);
        txtHealthCondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealthConditionActionPerformed(evt);
            }
        });
        jPanel1.add(txtHealthCondition, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 260, 30));

        cmbVaccinationCenter.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        cmbVaccinationCenter.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cmbVaccinationCenterPopupMenuWillBecomeVisible(evt);
            }
        });
        cmbVaccinationCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVaccinationCenterActionPerformed(evt);
            }
        });
        jPanel1.add(cmbVaccinationCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 220, -1));

        cmbState.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        cmbState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Johor", "Negeri Sembilan", "Malacca", "Selangor", "Kuala Lumpur", "Putrajaya", "Labuan", "Perak", "Penang", "Kedah", "Perlis", "Terengganu", "Kelantan", "Pahang", "Sabah ", "Sarawak" }));
        jPanel1.add(cmbState, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 150, 30));

        btnsubmitregistration.setBackground(new java.awt.Color(82, 137, 128));
        btnsubmitregistration.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnsubmitregistration.setText("Submit");
        btnsubmitregistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitregistrationActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubmitregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closecontactyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closecontactyesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closecontactyesActionPerformed

    private void closecontactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closecontactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closecontactnoActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtIcPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIcPassportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIcPassportActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    int dialog = JOptionPane.showConfirmDialog (null, "Are you sure you want to exit this application?", "Exit System", JOptionPane.YES_NO_OPTION);
    if(dialog == JOptionPane.YES_OPTION){
        dispose();
    }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btncancelregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelregistrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelregistrationActionPerformed

    private void btncancelregistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelregistrationMouseClicked
        int dialog = JOptionPane.showConfirmDialog (null, "Are you sure you want cancel registration?", "Cancel Registration", JOptionPane.YES_NO_OPTION);
        if(dialog == JOptionPane.YES_OPTION){
            PeopleMainMenu peoplemenu = new PeopleMainMenu();
            peoplemenu.setVisible(true);
            this.setVisible(false);
        }  
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelregistrationMouseClicked

    private void txtHealthConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealthConditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealthConditionActionPerformed

    private void cmbVaccinationCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVaccinationCenterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVaccinationCenterActionPerformed

    private void btnsubmitregistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitregistrationActionPerformed
        //Validate vaccination center (check if selected)
        if (cmbVaccinationCenter.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Please select a vaccination center", "Invalid Data Entered", JOptionPane.ERROR_MESSAGE);
            return;
        }
                
        //Retrive data from form
        String registrationId, name, icpassport, contact, email, closecontact, healthcondition, state, preferredcentre;

        registrationId = lblRegistrationId.getText();
        name = txtName.getText();
        icpassport = txtIcPassport.getText();
        contact = txtContact.getText();
        email = txtEmail.getText();
        healthcondition = txtHealthCondition.getText();
        state = cmbState.getSelectedItem().toString();
        preferredcentre = cmbVaccinationCenter.getSelectedItem().toString();

        if(closecontactno.isSelected()){
            closecontact = closecontactno.getText();
        }else{
            closecontact = closecontactyes.getText();
        }

        //Verify that all input are filled
        if(name.isEmpty() || icpassport.isEmpty() || contact.isEmpty() || email.isEmpty() || healthcondition.isEmpty() || closecontact.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please ensure that all fields have been filled in", "Invalid Data Entered", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Creates an instance of VaccinationAppointment and save it to database
        VaccineRegistration registervaccine = new VaccineRegistration(registrationId, name, icpassport, contact, email, closecontact, healthcondition, state, preferredcentre);
        VaccineRegistration.saveRegistration(registervaccine);

        PeopleMainMenu peoplemenu = new PeopleMainMenu();
        peoplemenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnsubmitregistrationActionPerformed

    private void cmbVaccinationCenterPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbVaccinationCenterPopupMenuWillBecomeVisible
        ArrayList<String> centerList = new ArrayList<>();
        ArrayList<VaccinationCenter> allCenter = new ArrayList<>();
        Collection<String> availableCenter;

        //Retrieve the file path based on the state
        String state = cmbState.getSelectedItem().toString();
        String filePath = State.getStateFileDirectory(state, "VaccinationCenter");

        //Retrive all files in the respective state folder
        allCenter = VaccinationCenter.getAllVaccinationCenters(filePath);
        for (VaccinationCenter vc : allCenter) {
            //Add all relevant vaccination center name into array list
            centerList.add(vc.getVaccinationCenterName());
        }
        
        availableCenter = centerList; 

        //Add Vaccination Center Name List to combo box
        DefaultComboBoxModel<String> centerSelector = new DefaultComboBoxModel();
        centerSelector.addAll(availableCenter);
        cmbVaccinationCenter.setModel(centerSelector);
 
    }//GEN-LAST:event_cmbVaccinationCenterPopupMenuWillBecomeVisible

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        lblRegistrationId.setText(VaccineRegistration.generateRegistrationId());
        System.out.println(lblRegistrationId.getText());
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeopleRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeopleRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeopleRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeopleRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeopleRegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelregistration;
    private javax.swing.JButton btnsubmitregistration;
    private javax.swing.ButtonGroup closecontact;
    private javax.swing.JRadioButton closecontactno;
    private javax.swing.JRadioButton closecontactyes;
    private javax.swing.JComboBox<String> cmbState;
    private javax.swing.JComboBox<String> cmbVaccinationCenter;
    private javax.swing.ButtonGroup healthcondition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRegistrationId;
    private javax.swing.ButtonGroup registerfor;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHealthCondition;
    private javax.swing.JTextField txtIcPassport;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
